/**
  ******************************************************************************
  * Redirecting printf to UART for debugging purposes
  *
  ******************************************************************************
  * @Implementation guidelines
  *  
  * NOTE: This code has been tested with ARM Cortex M MCUs with RTOS.
  * NOTE: In order for this code to work, UART driver has to be initialized
  *       in the program
  *
  ******************************************************************************/
  


/*****************************************************************************
 * STEP 1 : Implement the following code in the main.c file after all function 
 *          prototypes and variable declarations
 * 
 * 
 ****************************************************************************/

#ifdef __GNUC__

  /* With GCC/RAISONANCE, small printf (option LD Linker->Libraries->Small printf
     set to 'Yes') calls __io_putchar() */
 
  #define PUTCHAR_PROTOTYPE int __io_putchar(int ch)

#else
 
  #define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)

#endif /* __GNUC__ */


/*****************************************************************************
 * STEP 2 : Implement the fputc function
 *   
 * NOTE   : This function has to be place after declration of UART driver
 *          also, depending on MCU and UART driver used, the transmit function
 *          call might change. The (uint8_t *)&ch should remain constant
 *          independent of the driver used. In this code, HAL UART driver 
 *          generated by CubeMX for STM32F0 is used.
 * 
 * NOTE   : This code does not use the interrupt function for UART driver
 ****************************************************************************/
  
PUTCHAR_PROTOTYPE{

    HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1,0Xfff);
    return ch;

}


/*****************************************************************************
 * USE CASE : Simply use printf() function any where in the code
 ****************************************************************************/

while(1){

    int counter;
    printf("Sample Debug Message %i\n",counter);
    counter++;
    osDelay(200); //osDelay is from RTOS
    
}